"""changed the loanrepayment.

Revision ID: 1ec52f388195
Revises: 6603b550f02c
Create Date: 2025-05-06 07:40:34.679870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec52f388195'
down_revision = '6603b550f02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('actual_completion_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_completion_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
