"""Initial migration.

Revision ID: 275c14d8a26a
Revises: 30bcfd6e0475
Create Date: 2025-05-04 23:08:45.889920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275c14d8a26a'
down_revision = '30bcfd6e0475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_months', sa.Integer(), nullable=True))
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('term_months')

    # ### end Alembic commands ###
