"""added property in the loan model

Revision ID: 6603b550f02c
Revises: 275c14d8a26a
Create Date: 2025-05-05 06:20:24.947852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6603b550f02c'
down_revision = '275c14d8a26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_completion_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('actual_completion_date')

    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
